---

- name: Check if Logging Agent is installed
  stat:
    path: "/opt/google-fluentd/usr/sbin/google-fluentd"
  register: google_fluentd_installed

- name: Download the Logging Agent
  get_url:
    url: https://dl.google.com/cloudagents/install-logging-agent.sh
    dest: "/tmp/install-logging-agent.sh"
    mode: "+x"
  when: google_fluentd_installed.stat.exists == False

- name: Install the Logging Agent
  shell: "/tmp/install-logging-agent.sh"
  when: google_fluentd_installed.stat.exists == False

- name: Create active configurations folder
  file:
    path: "/etc/google-fluentd/config-active.d"
    state: directory

- name: Copy configuration file
  template:
    src: google-fluentd.conf.j2
    dest: "/etc/google-fluentd/google-fluentd.conf"
    backup: yes
  notify: restart google-fluentd

- name: Include specific for not GCP VM playbook
  include: not_gcp_vm.yml
  when: google_fluentd_not_gcp_vm

- name: Copy custom configurations
  copy:
    src: "{{ item }}"
    dest: "/etc/google-fluentd/config.d/{{ item | basename }}"
    backup: yes
  with_items: "{{ google_fluent_custom_config_files }}"
  notify: restart google-fluentd

- name: Copy custom configurations
  template:
    src: "{{ item }}"
    dest: "/etc/google-fluentd/config.d/{{ item | basename | regex_search('(.+\\.conf)') }}"
    backup: yes
  with_items: "{{ google_fluent_custom_config_templates }}"
  notify: restart google-fluentd

- name: Active configurations
  file:
    path: "/etc/google-fluentd/config-active.d/{{ item }}"
    src: "/etc/google-fluentd/config.d/{{ item }}"
    state: link
  with_items: "{{ google_fluent_active_configs }}"
  notify: restart google-fluentd

- name: Capture not enabled configs
  find:
    paths: "/etc/google-fluentd/config-active.d/"
    file_type: link
    excludes: "{{ google_fluent_active_configs }}"
  register: not_enabled_configs

- name: Remove not enabled configs
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ not_enabled_configs['files'] }}"
  notify: restart google-fluentd

- name: Include tasks to setup rsyslog for GCP logging
  include: rsyslog.yml
  when: google_fluentd_setup_rsyslog_for_gcp

- name: Install ruby dependencies
  apt:
    pkg:
      - gcc
      - make
      - ruby
      - ruby-dev
  when: google_fluentd_install_additional_gems

- name: Install fluentd additionals gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  when: google_fluentd_install_additional_gems
  with_items: "{{ google_fulentd_additional_gems_list }}"
  notify: restart google-fluentd

- name: Include journald-specific configuration.yml
  include: journald.yml
  when: google_fluentd_journald_monitoring_services|length > 0
